name: PHP Composer Test

on:
  push:
    branches: [ "action-test" ]
  pull_request:
    branches: [ "action-test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
          
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
          
     - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3.9'  # 指定 PHP 版本，可以根据需求?整
        extensions: mbstring, xdebug

    - name: Configure Xdebug
      run: |
        echo "xdebug.mode=coverage" >> /etc/php/8.3.9/cli/conf.d/20-xdebug.ini
        echo "xdebug.start_with_request=yes" >> /etc/php/8.3.9/cli/conf.d/20-xdebug.ini


    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
          
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run tests
      run: vendor/bin/phpunit --coverage-text
